/**
 * Category blueprints for the **demo** provider.
 *
 * Everything in this folder is generated sample data used to demonstrate the
 * product without a business-data provider. It never claims to describe a real
 * business: names, phone numbers (555-01xx / reserved demo ranges) and websites
 * are fictional. A live provider replaces this folder entirely — see
 * `src/lib/providers/index.ts`.
 */

export interface CategoryBlueprint {
  id: string;
  /** Singular display label, e.g. "Barber Shop". */
  label: string;
  pluralLabel: string;
  /** Match terms used to resolve a free-text search into this category. */
  keywords: string[];
  nameHeads: string[];
  nameTails: string[];
  specialties: string[];
  descriptionTemplates: string[];
  /** A booking/order flow is a normal expectation for these businesses. */
  bookingRelevant: boolean;
  menuRelevant: boolean;
  /** Probability the business has a website (demo distribution). */
  websiteChance: number;
  /** Probability an existing site shows gaps worth flagging (demo distribution). */
  needsImprovementRate: number;
  avgRating: number;
  priceLevel: [number, number];
  /** Email local-parts typical for the category. */
  emailPrefixes: string[];
  /** Fallback classification when a search term matches nothing. */
  related: string[];
}

export const CATEGORY_BLUEPRINTS: CategoryBlueprint[] = [
  {
    id: "barber",
    label: "Barber Shop",
    pluralLabel: "Barber Shops",
    keywords: ["barber", "barbershop", "barber shop", "fade", "haircut", "mens grooming", "shave"],
    nameHeads: [
      "Elite",
      "Prime",
      "Sharp Line",
      "Urban",
      "Northside",
      "Precision",
      "Royal",
      "Eastside",
      "Golden Blade",
      "The Cutting Room",
      "Southside",
      "Metro",
      "Legacy",
      "Crown",
    ],
    nameTails: [
      "Barber Shop",
      "Barbershop",
      "Cuts",
      "Cuts & Shaves",
      "Grooming Co.",
      "Fade Co.",
      "Barber Studio",
    ],
    specialties: ["skin fades", "beard trims", "hot towel shaves", "kids cuts", "line-ups", "hair designs"],
    descriptionTemplates: [
      "{name} is a neighbourhood {category} serving {city} with {s1}, {s2} and {s3}. Walk-ins are welcome and appointments can be booked by phone.",
      "Family-owned {category} in {city} offering {s1}, {s2} and {s3} in a relaxed, no-rush environment.",
      "{name} has been cutting hair in {city} for {years} years, with a focus on {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.62,
    needsImprovementRate: 0.34,
    avgRating: 4.6,
    priceLevel: [1, 2],
    emailPrefixes: ["hello", "info", "bookings", "contact"],
    related: ["hair_salon", "spa"],
  },
  {
    id: "hair_salon",
    label: "Hair Salon",
    pluralLabel: "Hair Salons",
    keywords: ["hair salon", "salon", "hairdresser", "hairstylist", "stylist", "blowout", "weave"],
    nameHeads: [
      "Luxe",
      "Bella",
      "Glow",
      "The Loft",
      "Serenity",
      "Halo",
      "Mane",
      "Studio 62",
      "Velvet",
      "Aura",
      "Bloom",
      "Radiant",
    ],
    nameTails: ["Hair Studio", "Salon", "Hair Lounge", "Beauty Bar", "Salon & Spa", "Hair Co."],
    specialties: ["balayage", "colour correction", "keratin treatments", "bridal styling", "extensions", "trims"],
    descriptionTemplates: [
      "{name} offers {s1}, {s2} and {s3} for clients across {city}. Consultations are available by appointment.",
      "A modern {category} in {city} specialising in {s1} and {s2}, with {s3} available on request.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.7,
    needsImprovementRate: 0.38,
    avgRating: 4.7,
    priceLevel: [2, 3],
    emailPrefixes: ["hello", "bookings", "info", "reception"],
    related: ["spa", "nail_salon"],
  },
  {
    id: "nail_salon",
    label: "Nail Salon",
    pluralLabel: "Nail Salons",
    keywords: ["nail", "nails", "manicure", "pedicure", "nail salon", "gel"],
    nameHeads: ["Polished", "Tips & Toes", "Luxe Nails", "City Nails", "Bliss", "Shine", "Pure", "Zen"],
    nameTails: ["Nail Spa", "Nails", "Nail Bar", "Nail Studio", "Beauty Lounge"],
    specialties: ["gel manicures", "acrylic sets", "spa pedicures", "nail art", "dip powder"],
    descriptionTemplates: [
      "{name} provides {s1}, {s2} and {s3} in {city}. Walk-ins and appointments are both welcome.",
      "Friendly {category} in {city} known for {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.48,
    needsImprovementRate: 0.44,
    avgRating: 4.5,
    priceLevel: [1, 2],
    emailPrefixes: ["info", "hello", "bookings"],
    related: ["hair_salon", "spa"],
  },
  {
    id: "spa",
    label: "Spa & Wellness",
    pluralLabel: "Spas",
    keywords: ["spa", "massage", "wellness", "facial", "day spa", "skincare"],
    nameHeads: ["Tranquil", "The Retreat", "Calm", "Lotus", "Balance", "Oasis", "Renew", "Still Water"],
    nameTails: ["Day Spa", "Spa & Wellness", "Wellness Studio", "Massage & Spa", "Skin Studio"],
    specialties: ["deep tissue massage", "facials", "body treatments", "couples massage", "aromatherapy"],
    descriptionTemplates: [
      "{name} offers {s1}, {s2} and {s3} in a quiet setting in {city}. Bookings are taken by phone or email.",
      "A boutique {category} in {city} focused on {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.72,
    needsImprovementRate: 0.3,
    avgRating: 4.8,
    priceLevel: [3, 4],
    emailPrefixes: ["hello", "bookings", "reception"],
    related: ["hair_salon"],
  },
  {
    id: "restaurant",
    label: "Restaurant",
    pluralLabel: "Restaurants",
    keywords: ["restaurant", "food", "diner", "eatery", "bistro", "kitchen", "grill", "pizza", "sushi", "bbq"],
    nameHeads: [
      "The Copper Fork",
      "Mama Rosa's",
      "Smoke & Oak",
      "Harbour",
      "Little Sicily",
      "Basil & Vine",
      "Iron Skillet",
      "Northern",
      "Saffron",
      "Corner Table",
    ],
    nameTails: ["Kitchen", "Grill", "Restaurant", "Bistro", "Bar & Kitchen", "Diner", "Eatery"],
    specialties: ["seasonal menus", "wood-fired dishes", "vegetarian options", "family-style dining", "specials"],
    descriptionTemplates: [
      "{name} serves {s1}, {s2} and {s3} in {city}. Reservations are recommended for weekend evenings.",
      "A casual {category} in {city} with {s1} and {s2} on the menu.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.78,
    needsImprovementRate: 0.4,
    avgRating: 4.5,
    priceLevel: [2, 3],
    emailPrefixes: ["info", "hello", "reservations"],
    related: ["cafe", "bakery"],
  },
  {
    id: "cafe",
    label: "Coffee Shop",
    pluralLabel: "Coffee Shops",
    keywords: ["coffee", "cafe", "café", "espresso", "tea house", "coffee shop"],
    nameHeads: ["Bean There", "Morning", "Roast", "The Daily", "Filter", "Kettle", "Sunrise", "Steam"],
    nameTails: ["Coffee", "Coffee House", "Café", "Roasters", "Espresso Bar", "Coffee Co."],
    specialties: ["single-origin roasts", "pastries", "cold brew", "breakfast", "wifi workspace"],
    descriptionTemplates: [
      "{name} is a {category} in {city} serving {s1} and {s2}.",
      "Independent {category} in {city} with {s1} and {s2}, open early seven days a week.",
    ],
    bookingRelevant: false,
    menuRelevant: true,
    websiteChance: 0.58,
    needsImprovementRate: 0.42,
    avgRating: 4.6,
    priceLevel: [1, 2],
    emailPrefixes: ["hello", "info"],
    related: ["bakery", "restaurant"],
  },
  {
    id: "bakery",
    label: "Bakery",
    pluralLabel: "Bakeries",
    keywords: ["bakery", "cake", "pastry", "bread", "cupcake", "dessert"],
    nameHeads: ["Sweet Rise", "Golden Crust", "Flour & Co", "Butter Lane", "Sunday", "Honey"],
    nameTails: ["Bakery", "Bake Shop", "Patisserie", "Cakes", "Baking Co."],
    specialties: ["custom cakes", "sourdough", "wedding cakes", "vegan bakes", "dessert boxes"],
    descriptionTemplates: [
      "{name} bakes {s1}, {s2} and {s3} fresh daily in {city}.",
      "Family-run {category} in {city} taking orders for {s1} and {s2}.",
    ],
    bookingRelevant: false,
    menuRelevant: true,
    websiteChance: 0.52,
    needsImprovementRate: 0.46,
    avgRating: 4.8,
    priceLevel: [1, 2],
    emailPrefixes: ["orders", "hello", "info"],
    related: ["cafe"],
  },
  {
    id: "hotel",
    label: "Hotel",
    pluralLabel: "Hotels",
    keywords: ["hotel", "lodging", "motel", "inn", "guest house", "suites", "accommodation", "bnb"],
    nameHeads: ["The Wilton", "Grand", "Riverside", "Haven", "Copper Creek", "Maple", "Bayview", "Stonebridge"],
    nameTails: ["Hotel", "Inn", "Suites", "Guest House", "Boutique Hotel", "Lodge"],
    specialties: ["conference rooms", "airport shuttle", "breakfast included", "pet friendly rooms", "event spaces"],
    descriptionTemplates: [
      "{name} offers {s1}, {s2} and {s3} for guests visiting {city}. Rooms can be booked online or by phone.",
      "A {category} in central {city} with {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.86,
    needsImprovementRate: 0.36,
    avgRating: 4.4,
    priceLevel: [2, 4],
    emailPrefixes: ["reservations", "frontdesk", "info"],
    related: ["restaurant"],
  },
  {
    id: "dental",
    label: "Dental Clinic",
    pluralLabel: "Dental Clinics",
    keywords: ["dentist", "dental", "dental clinic", "orthodontist", "teeth", "hygienist"],
    nameHeads: ["Bright Smile", "Riverside", "Northgate", "Smile Studio", "Parkview", "Cedar", "Summit"],
    nameTails: ["Dental", "Dental Care", "Dental Clinic", "Family Dentistry", "Dental Group"],
    specialties: ["routine cleanings", "teeth whitening", "cosmetic dentistry", "emergency appointments", "invisalign"],
    descriptionTemplates: [
      "{name} provides {s1}, {s2} and {s3} at its {city} practice. New patients can request an appointment online.",
      "A family-focused {category} in {city} offering {s1}, {s2} and {s3}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.9,
    needsImprovementRate: 0.28,
    avgRating: 4.7,
    priceLevel: [3, 4],
    emailPrefixes: ["appointments", "frontdesk", "info"],
    related: ["medical_clinic"],
  },
  {
    id: "medical_clinic",
    label: "Medical Clinic",
    pluralLabel: "Medical Clinics",
    keywords: ["clinic", "doctor", "medical", "physician", "health centre", "health center", "gp"],
    nameHeads: ["Riverbend", "Harbour", "Fairview", "Lakeside", "Central", "Parkway", "Wellspring"],
    nameTails: ["Medical Clinic", "Family Practice", "Health Centre", "Medical Group", "Clinic"],
    specialties: ["same-day appointments", "preventive care", "paediatrics", "chronic care", "vaccinations"],
    descriptionTemplates: [
      "{name} is a {category} in {city} providing {s1}, {s2} and {s3}. Appointments can be requested by phone.",
      "{name} serves {city} with {s1}, {s2} and {s3}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.84,
    needsImprovementRate: 0.34,
    avgRating: 4.5,
    priceLevel: [3, 4],
    emailPrefixes: ["reception", "appointments", "info"],
    related: ["dental"],
  },
  {
    id: "gym",
    label: "Gym & Fitness",
    pluralLabel: "Gyms",
    keywords: ["gym", "fitness", "crossfit", "personal training", "health club", "boxing"],
    nameHeads: ["Iron", "Peak", "Northside", "Forge", "Lift", "Momentum", "Alpha", "Summit"],
    nameTails: ["Fitness", "Gym", "Strength Co.", "Athletic Club", "Training Studio", "Performance"],
    specialties: ["personal training", "group classes", "free weights", "day passes", "nutrition coaching"],
    descriptionTemplates: [
      "{name} offers {s1}, {s2} and {s3} with memberships from monthly to annual. Free trial sessions are available.",
      "A community {category} in {city} with {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.8,
    needsImprovementRate: 0.42,
    avgRating: 4.6,
    priceLevel: [2, 3],
    emailPrefixes: ["hello", "membership", "info"],
    related: ["yoga", "spa"],
  },
  {
    id: "yoga",
    label: "Yoga Studio",
    pluralLabel: "Yoga Studios",
    keywords: ["yoga", "pilates", "studio", "meditation", "barre"],
    nameHeads: ["Still", "Breath", "Flow", "Grounded", "Lotus", "Sunrise", "Balance"],
    nameTails: ["Yoga", "Yoga Studio", "Pilates Studio", "Movement Studio", "Wellness"],
    specialties: ["beginner classes", "vinyasa", "prenatal yoga", "mat pilates", "workshops"],
    descriptionTemplates: [
      "{name} runs {s1}, {s2} and {s3} throughout the week in {city}.",
      "A small {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.7,
    needsImprovementRate: 0.4,
    avgRating: 4.8,
    priceLevel: [2, 3],
    emailPrefixes: ["hello", "studio", "info"],
    related: ["gym"],
  },
  {
    id: "real_estate",
    label: "Real Estate Agency",
    pluralLabel: "Real Estate Agencies",
    keywords: ["real estate", "realtor", "property", "estate agent", "lettings", "broker"],
    nameHeads: ["Keystone", "Homefront", "North Point", "Landmark", "Cornerstone", "Vista", "Oak & Stone"],
    nameTails: ["Realty", "Real Estate", "Properties", "Property Group", "Homes", "Estates"],
    specialties: ["home valuations", "buyer representation", "rentals", "investment properties", "open houses"],
    descriptionTemplates: [
      "{name} helps buyers and sellers across {city} with {s1}, {s2} and {s3}.",
      "An independent {category} in {city} covering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.92,
    needsImprovementRate: 0.3,
    avgRating: 4.6,
    priceLevel: [2, 3],
    emailPrefixes: ["info", "sales", "hello"],
    related: ["car_dealership"],
  },
  {
    id: "car_dealership",
    label: "Car Dealership",
    pluralLabel: "Car Dealerships",
    keywords: ["car dealership", "auto dealer", "cars", "vehicle", "used cars", "motors"],
    nameHeads: ["Summit", "Metro", "Prestige", "Valley", "Autohaus", "Riverside", "Gateway"],
    nameTails: ["Motors", "Auto Group", "Motorsports", "Auto Sales", "Cars"],
    specialties: ["used vehicle sales", "financing", "trade-ins", "service centre", "test drives"],
    descriptionTemplates: [
      "{name} sells and services vehicles in {city}, offering {s1}, {s2} and {s3}.",
      "A {category} in {city} with {s1} and {s2} available by appointment.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.88,
    needsImprovementRate: 0.34,
    avgRating: 4.4,
    priceLevel: [3, 4],
    emailPrefixes: ["sales", "info", "frontdesk"],
    related: ["auto_repair"],
  },
  {
    id: "auto_repair",
    label: "Auto Repair Shop",
    pluralLabel: "Auto Repair Shops",
    keywords: ["auto repair", "mechanic", "garage", "car service", "tyres", "tires", "car repair"],
    nameHeads: ["Trusty", "Precision", "Main Street", "Allpro", "Northside", "Torque", "Fairway"],
    nameTails: ["Auto Repair", "Garage", "Auto Service", "Mechanics", "Car Care"],
    specialties: ["brake repairs", "diagnostics", "oil changes", "tyre fitting", "inspections"],
    descriptionTemplates: [
      "{name} handles {s1}, {s2} and {s3} for drivers in {city}. Quotes are given by phone.",
      "An independent {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.52,
    needsImprovementRate: 0.5,
    avgRating: 4.5,
    priceLevel: [2, 3],
    emailPrefixes: ["service", "info"],
    related: ["car_dealership"],
  },
  {
    id: "law_firm",
    label: "Law Firm",
    pluralLabel: "Law Firms",
    keywords: ["lawyer", "law firm", "attorney", "solicitor", "legal", "notary"],
    nameHeads: ["Hartley & Moss", "Whitfield", "Bennet Legal", "Ashford", "Okonkwo", "Sterling"],
    nameTails: ["Law", "Legal", "Law Group", "Attorneys", "Solicitors", "Legal Practice"],
    specialties: ["family law", "contracts", "immigration", "business law", "estate planning"],
    descriptionTemplates: [
      "{name} advises clients in {city} on {s1}, {s2} and {s3}. Consultations can be booked by phone.",
      "A boutique {category} in {city} covering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.86,
    needsImprovementRate: 0.3,
    avgRating: 4.7,
    priceLevel: [3, 4],
    emailPrefixes: ["enquiries", "info", "contact"],
    related: ["accountant"],
  },
  {
    id: "accountant",
    label: "Accounting Firm",
    pluralLabel: "Accounting Firms",
    keywords: ["accountant", "accounting", "bookkeeping", "tax", "cpa", "payroll"],
    nameHeads: ["Ledger", "Northbridge", "Clarity", "Summit", "Adeyemi", "Cornerstone"],
    nameTails: ["Accounting", "Bookkeeping", "Tax Services", "Financial", "Advisors"],
    specialties: ["tax preparation", "payroll", "bookkeeping", "year-end accounts", "business advisory"],
    descriptionTemplates: [
      "{name} supports small businesses in {city} with {s1}, {s2} and {s3}.",
      "An independent {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.74,
    needsImprovementRate: 0.38,
    avgRating: 4.8,
    priceLevel: [2, 3],
    emailPrefixes: ["info", "enquiries", "hello"],
    related: ["law_firm"],
  },
  {
    id: "pet_grooming",
    label: "Pet Grooming",
    pluralLabel: "Pet Groomers",
    keywords: ["pet grooming", "groomer", "dog grooming", "pet salon", "dog wash", "vet"],
    nameHeads: ["Wag & Wash", "Pawfect", "Happy Tails", "Furry", "Bark Ave", "Paws"],
    nameTails: ["Pet Grooming", "Grooming Salon", "Pet Spa", "Dog Grooming", "Pet Care"],
    specialties: ["dog grooming", "cat grooming", "nail clipping", "de-shedding", "puppy first visits"],
    descriptionTemplates: [
      "{name} provides {s1}, {s2} and {s3} in {city}. Appointments are taken by phone or text.",
      "A friendly {category} in {city} known for {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.55,
    needsImprovementRate: 0.46,
    avgRating: 4.7,
    priceLevel: [2, 3],
    emailPrefixes: ["hello", "bookings", "info"],
    related: ["spa"],
  },
  {
    id: "cleaning",
    label: "Cleaning Service",
    pluralLabel: "Cleaning Services",
    keywords: ["cleaning", "cleaner", "housekeeping", "maid service", "janitorial", "laundry"],
    nameHeads: ["Spotless", "Fresh Start", "Bright & Tidy", "Pure", "Sparkle", "Green Door"],
    nameTails: ["Cleaning", "Cleaning Services", "Home Care", "Facilities", "Clean Co."],
    specialties: ["deep cleans", "move-out cleans", "office cleaning", "recurring visits", "carpet cleaning"],
    descriptionTemplates: [
      "{name} covers {s1}, {s2} and {s3} across {city}. Free quotes are available on request.",
      "A local {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.46,
    needsImprovementRate: 0.48,
    avgRating: 4.6,
    priceLevel: [1, 3],
    emailPrefixes: ["hello", "quotes", "info"],
    related: ["landscaping"],
  },
  {
    id: "landscaping",
    label: "Landscaping",
    pluralLabel: "Landscapers",
    keywords: ["landscaping", "gardening", "lawn", "tree service", "hardscaping", "irrigation"],
    nameHeads: ["Evergreen", "GreenWorks", "Stone & Soil", "Hillside", "Yard Pro", "Cedar"],
    nameTails: ["Landscaping", "Lawn Care", "Garden Services", "Outdoor Living", "Tree Care"],
    specialties: ["lawn maintenance", "garden design", "tree trimming", "irrigation systems", "seasonal cleanups"],
    descriptionTemplates: [
      "{name} handles {s1}, {s2} and {s3} for homes and businesses in {city}.",
      "A family-run {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.5,
    needsImprovementRate: 0.5,
    avgRating: 4.6,
    priceLevel: [1, 3],
    emailPrefixes: ["info", "quotes", "hello"],
    related: ["cleaning"],
  },
  {
    id: "photography",
    label: "Photography Studio",
    pluralLabel: "Photography Studios",
    keywords: ["photography", "photographer", "studio", "videographer", "wedding photos"],
    nameHeads: ["Frame", "Golden Hour", "Lens & Light", "Storybook", "Northlight", "Aperture"],
    nameTails: ["Photography", "Studios", "Photo Co.", "Imagery", "Visuals"],
    specialties: ["wedding photography", "portrait sessions", "product shoots", "event coverage", "headshots"],
    descriptionTemplates: [
      "{name} shoots {s1}, {s2} and {s3} around {city}. Packages are quoted per project.",
      "A {category} in {city} specialising in {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.82,
    needsImprovementRate: 0.36,
    avgRating: 4.9,
    priceLevel: [2, 4],
    emailPrefixes: ["hello", "bookings", "info"],
    related: ["event_venue"],
  },
  {
    id: "event_venue",
    label: "Event Venue",
    pluralLabel: "Event Venues",
    keywords: ["venue", "event space", "wedding venue", "banquet", "hall", "conference"],
    nameHeads: ["The Loft", "Riverbend", "Garden Room", "Ironworks", "Rosewood", "Skyline"],
    nameTails: ["Venue", "Events", "Event Space", "Banquet Hall", "Events Centre"],
    specialties: ["wedding receptions", "corporate events", "private parties", "catering packages", "AV equipment"],
    descriptionTemplates: [
      "{name} hosts {s1}, {s2} and {s3} in {city}. Site visits can be arranged by appointment.",
      "A {category} in {city} suited to {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: true,
    websiteChance: 0.8,
    needsImprovementRate: 0.4,
    avgRating: 4.7,
    priceLevel: [3, 4],
    emailPrefixes: ["events", "bookings", "info"],
    related: ["photography", "restaurant"],
  },
  {
    id: "tattoo",
    label: "Tattoo Studio",
    pluralLabel: "Tattoo Studios",
    keywords: ["tattoo", "tattoo studio", "piercing", "ink"],
    nameHeads: ["Ink & Iron", "Black Lantern", "Steady Hand", "Rose & Thorn", "North Ink", "True Lines"],
    nameTails: ["Tattoo", "Tattoo Studio", "Tattoo Co.", "Ink Studio", "Body Art"],
    specialties: ["custom tattoos", "fine line work", "cover-ups", "piercings", "consultations"],
    descriptionTemplates: [
      "{name} takes bookings for {s1}, {s2} and {s3} in {city}.",
      "A {category} in {city} focused on {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.6,
    needsImprovementRate: 0.44,
    avgRating: 4.8,
    priceLevel: [2, 3],
    emailPrefixes: ["bookings", "hello", "info"],
    related: ["barber"],
  },
  {
    id: "florist",
    label: "Florist",
    pluralLabel: "Florists",
    keywords: ["florist", "flower", "flowers", "bouquet", "plant shop"],
    nameHeads: ["Petal", "Wild Stem", "Bloom Room", "Fern & Fig", "Garden Gate"],
    nameTails: ["Florist", "Flowers", "Floral Studio", "Flower Shop", "Botanicals"],
    specialties: ["wedding flowers", "same-day delivery", "sympathy arrangements", "subscription bouquets"],
    descriptionTemplates: [
      "{name} creates {s1}, {s2} and {s3} with delivery across {city}.",
      "A neighbourhood {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: false,
    menuRelevant: true,
    websiteChance: 0.54,
    needsImprovementRate: 0.46,
    avgRating: 4.8,
    priceLevel: [2, 3],
    emailPrefixes: ["orders", "hello", "info"],
    related: ["bakery"],
  },
  {
    id: "electrician",
    label: "Electrician",
    pluralLabel: "Electricians",
    keywords: ["electrician", "electrical", "wiring", "solar", "generator", "lighting"],
    nameHeads: ["Voltek", "Bright Spark", "Circuit", "Current", "Northline", "Amped"],
    nameTails: ["Electrical", "Electric", "Electrical Services", "Power Solutions", "Electricals"],
    specialties: ["emergency call-outs", "rewiring", "solar installs", "generator servicing", "lighting upgrades"],
    descriptionTemplates: [
      "{name} handles {s1}, {s2} and {s3} for homes and businesses in {city}. Quotes are given by phone.",
      "A licensed {category} in {city} covering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.4,
    needsImprovementRate: 0.52,
    avgRating: 4.5,
    priceLevel: [1, 3],
    emailPrefixes: ["info", "quotes", "hello"],
    related: ["plumbing"],
  },
  {
    id: "plumbing",
    label: "Plumbing Service",
    pluralLabel: "Plumbers",
    keywords: ["plumber", "plumbing", "drain", "water heater", "pipe repair"],
    nameHeads: ["Flowright", "Blue Pipe", "Reliant", "Mainline", "Aqua", "Steady Flow"],
    nameTails: ["Plumbing", "Plumbing & Heating", "Drain Services", "Plumbing Co.", "Home Services"],
    specialties: ["emergency repairs", "boiler servicing", "leak detection", "bathroom fitting", "drain clearing"],
    descriptionTemplates: [
      "{name} covers {s1}, {s2} and {s3} across {city}, with emergency call-outs available.",
      "A local {category} in {city} offering {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.42,
    needsImprovementRate: 0.5,
    avgRating: 4.5,
    priceLevel: [1, 3],
    emailPrefixes: ["info", "quotes", "service"],
    related: ["electrician"],
  },
];

/** Generic blueprint derived from anything the user types. */
export function genericBlueprint(term: string): CategoryBlueprint {
  const cleaned = term.trim().replace(/\s+/g, " ");
  const singular = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  return {
    id: "general",
    label: singular,
    pluralLabel: `${singular}s`,
    keywords: [cleaned.toLowerCase()],
    nameHeads: [
      "Premier",
      "Citywide",
      "Northside",
      "Trusted",
      "Cornerstone",
      "Summit",
      "Riverside",
      "Evergreen",
      "Metro",
      "Heritage",
    ],
    nameTails: [singular, `${singular} Co.`, `${singular} Services`, `The ${singular} Group`, `${singular} Studio`],
    specialties: ["personal service", "same-week bookings", "local coverage", "transparent pricing"],
    descriptionTemplates: [
      "{name} is a {category} in {city} offering {s1}, {s2} and {s3}.",
      "{name} serves clients across {city} with {s1} and {s2}.",
    ],
    bookingRelevant: true,
    menuRelevant: false,
    websiteChance: 0.55,
    needsImprovementRate: 0.45,
    avgRating: 4.6,
    priceLevel: [2, 3],
    emailPrefixes: ["hello", "info", "contact"],
    related: [],
  };
}

export function findBlueprint(term: string): CategoryBlueprint | null {
  const q = term.trim().toLowerCase();
  if (!q) return null;
  const stripped = q.replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ").trim();
  let best: { bp: CategoryBlueprint; score: number } | null = null;

  for (const bp of CATEGORY_BLUEPRINTS) {
    for (const kw of bp.keywords) {
      const score =
        stripped === kw
          ? 100
          : stripped.startsWith(kw) || kw.startsWith(stripped)
            ? 60 + Math.min(kw.length, 20)
            : stripped.includes(kw)
              ? 40 + Math.min(kw.length, 20)
              : 0;
      if (score > 0 && (!best || score > best.score)) best = { bp, score };
    }
  }
  return best?.bp ?? null;
}

export const CATEGORY_MAP: Record<string, CategoryBlueprint> = Object.fromEntries(
  CATEGORY_BLUEPRINTS.map((bp) => [bp.id, bp]),
);
