import { CATEGORY_MAP, genericBlueprint, type CategoryBlueprint } from "@/lib/providers/demo/categories";
import { CITY_PROFILES, fallbackCity, type CityProfile } from "@/lib/providers/demo/cities";
import { titleCase } from "@/lib/utils";

/**
 * Demo business ids are self-describing:
 *
 *   <category>-<cityKey>-r<radius>-<index>
 *   barber-columbus-oh-r25-143
 *   general-coffee-roastery-london-uk-r10-2
 *
 * Everything needed to regenerate the exact same record is encoded in the id, so a
 * shared or bookmarked detail link resolves even after a server restart — no
 * database required for the demo. A live provider simply returns its own ids.
 */

export const DEMO_ID_PATTERN = /^(?<prefix>.+)-r(?<radius>\d+)-(?<index>\d+)$/;

export function demoBusinessId(input: {
  blueprintId: string;
  categoryTerm?: string;
  cityKey: string;
  radiusMiles: number;
  index: number;
}) {
  const categoryPart =
    input.blueprintId === "general" && input.categoryTerm
      ? `general-${slug(input.categoryTerm)}`
      : input.blueprintId;
  return `${categoryPart}-${input.cityKey}-r${Math.round(input.radiusMiles)}-${input.index}`;
}

function slug(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export interface ParsedDemoId {
  blueprint: CategoryBlueprint;
  city: CityProfile;
  radiusMiles: number;
  index: number;
}

/** Longest city key that the prefix ends with — handles "port-harcourt-ng". */
function splitCityKey(prefix: string): { categoryPart: string; cityKey: string } | null {
  const keys = [...CITY_PROFILES.map((c) => c.key)].sort((a, b) => b.length - a.length);
  for (const key of keys) {
    if (prefix.endsWith(`-${key}`)) {
      return { categoryPart: prefix.slice(0, prefix.length - key.length - 1), cityKey: key };
    }
  }
  // Ad-hoc locations generated by `fallbackCity` use a `custom-<slug>` key.
  const custom = /^(?<categoryPart>.+)-custom-(?<slug>[a-z0-9-]+)$/.exec(prefix);
  if (custom?.groups) {
    return {
      categoryPart: custom.groups.categoryPart,
      cityKey: `custom-${custom.groups.slug}`,
    };
  }
  return null;
}

export function parseDemoId(id: string): ParsedDemoId | null {
  const match = DEMO_ID_PATTERN.exec(id);
  if (!match?.groups) return null;

  const prefix = match.groups.prefix;
  const radiusMiles = Number(match.groups.radius);
  const index = Number(match.groups.index);
  if (!Number.isFinite(radiusMiles) || !Number.isFinite(index)) return null;

  const split = splitCityKey(prefix);
  if (!split) return null;

  const { categoryPart, cityKey } = split;

  const city =
    CITY_PROFILES.find((c) => c.key === cityKey) ??
    (cityKey.startsWith("custom-")
      ? fallbackCity(titleCase(cityKey.replace(/^custom-/, "").replace(/-/g, " ")))
      : null);
  if (!city) return null;

  let blueprint: CategoryBlueprint | null = CATEGORY_MAP[categoryPart] ?? null;
  if (!blueprint && categoryPart.startsWith("general-")) {
    const term = categoryPart.replace(/^general-/, "").replace(/-/g, " ");
    blueprint = genericBlueprint(titleCase(term));
  }
  if (!blueprint) return null;

  return { blueprint, city, radiusMiles, index };
}
