import { AlertTriangle, BadgeCheck, CheckCircle2, CircleDashed, Globe, MinusCircle, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { CheckStatus, DataProvenance, WebsiteStatus } from "@/lib/types";

/**
 * Status badges.
 *
 * Colour carries meaning consistently across the app:
 *   green = verified / positive   blue = informational   yellow = needs attention
 *   grey = unknown or not supplied by the provider
 */

export function WebsiteStatusBadge({
  status,
  size = "md",
  className,
}: {
  status: WebsiteStatus;
  size?: "sm" | "md" | "lg";
  className?: string;
}) {
  const map: Record<WebsiteStatus, { label: string; variant: "green" | "neutral" | "yellow"; icon: React.ReactNode }> = {
    has_website: {
      label: "Has Website",
      variant: "green",
      icon: <CheckCircle2 />,
    },
    no_website: {
      label: "No Website",
      variant: "yellow",
      icon: <AlertTriangle />,
    },
    unknown_website_status: {
      label: "Website unchecked",
      variant: "neutral",
      icon: <CircleDashed />,
    },
  };
  const { label, variant, icon } = map[status];
  return (
    <Badge variant={variant} size={size} className={className}>
      {icon}
      {label}
    </Badge>
  );
}

export function CheckStatusBadge({ status, className }: { status: CheckStatus; className?: string }) {
  const map: Record<CheckStatus, { label: string; variant: "green" | "yellow" | "neutral" | "muted" }> = {
    good: { label: "Good", variant: "green" },
    needs_improvement: { label: "Needs Improvement", variant: "yellow" },
    unknown: { label: "Unknown", variant: "neutral" },
    not_checked: { label: "Not Checked", variant: "muted" },
  };
  const { label, variant } = map[status];
  return (
    <Badge variant={variant} size="sm" className={className}>
      {label}
    </Badge>
  );
}

export function OpportunityBadge({
  score,
  className,
}: {
  score: number;
  className?: string;
}) {
  const tone = score >= 70 ? "yellow" : score >= 45 ? "blue" : "neutral";
  const label = score >= 70 ? "High opportunity" : score >= 45 ? "Medium opportunity" : "Low opportunity";
  return (
    <Badge variant={tone} className={className}>
      {label}
    </Badge>
  );
}

export function ImpactBadge({ impact, className }: { impact: "high" | "medium" | "low"; className?: string }) {
  const map = {
    high: { label: "High impact", variant: "yellow" as const },
    medium: { label: "Medium impact", variant: "blue" as const },
    low: { label: "Low impact", variant: "neutral" as const },
  };
  return (
    <Badge variant={map[impact].variant} size="sm" className={className}>
      {map[impact].label}
    </Badge>
  );
}

export function VerifiedBadge({
  verified,
  size = "sm",
  className,
}: {
  verified: boolean;
  size?: "sm" | "md" | "lg";
  className?: string;
}) {
  return verified ? (
    <Badge variant="blue" size={size} className={className} title="The provider marks this listing as claimed by the business">
      <BadgeCheck />
      Verified listing
    </Badge>
  ) : (
    <Badge variant="muted" size={size} className={className} title="The provider does not mark this listing as claimed">
      <MinusCircle />
      Unclaimed
    </Badge>
  );
}

/**
 * Always tells the user where a record came from — demo sample data vs a live
 * vendor vs AI-generated analysis.
 */
export function ProvenanceBadge({
  provenance,
  className,
}: {
  provenance: Pick<DataProvenance, "kind" | "providerLabel">;
  className?: string;
}) {
  if (provenance.kind === "demo") {
    return (
      <Badge
        variant="neutral"
        size="sm"
        className={cn("border-dashed", className)}
        title="Generated sample data used to demonstrate the product"
      >
        <CircleDashed />
        Demo data
      </Badge>
    );
  }
  return (
    <Badge variant="neutral" size="sm" className={className} title={`Source: ${provenance.providerLabel}`}>
      <ShieldCheck />
      {provenance.providerLabel}
    </Badge>
  );
}

export function AiGeneratedBadge({ className }: { className?: string }) {
  return (
    <Badge variant="yellow" size="sm" className={className} title="Generated by AI from the information available">
      AI-generated
    </Badge>
  );
}

export function WebsiteLinkBadge({ url, className }: { url: string | null; className?: string }) {
  if (!url) return null;
  return (
    <Badge variant="blue" size="sm" className={className}>
      <Globe />
      Website
    </Badge>
  );
}
